#!/usr/bin/env python3

if __name__ == '__main__':
    import os
    import sys
    print(f"This is a scons script; running it like that for you.")
    os.chdir(os.path.dirname(__file__))
    os.execvp('scons', ['scons', *sys.argv[1:]])

import os
import glob as _glob

def glob(pattern, files=True, dirs=False):
    for name in _glob.iglob(pattern, recursive=True):
        if files and os.path.isfile(name):
            yield name
        if dirs and os.path.isdir(name):
            yield name


env = Environment()

lib = env.SharedLibrary(
    target='chattor',
    source=list(glob('src/lib/**.c'))
)
Default(lib)

exe = env.Program(
    target='chattor',
    source=[]
)
