# Very nearly actions/starter-workflows' cmake.yml, but with a build matrix

name: automatic checks
on:
  push:
    branches: [ release, staging, feature/* ]
    tags: '*'
  pull_request:
    branches: [ release, staging, feature/* ]
jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        config: [ Debug, RelWithDebInfo, RelMinSize ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    # TODO: Figure out how to install libcunit on all platforms
    - name: Install prereqs
      run: sudo apt-get install valgrind libcunit1 libcunit1-doc libcunit1-dev
    - name: Info
      run: echo Building ${{ matrix.config }} on ${{ matrix.platform }}
    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.config }}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }}
    - name: Unit testing
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.config }} --output-on-failure
    - name: Integration testing
      run: echo Integration testing still needs to be implemented
    - name: Fuzz testing
      run: echo Fuzz testing still needs to be implemented
