# Very nearly actions/starter-workflows' cmake.yml, but with a build matrix

name: Automatic Tests
on:
  push:
    branches: [ release, staging, feature/* ]
    tags: '*'
  pull_request:
    branches: [ release, staging, feature/* ]
jobs:
  # main build and test is on ubuntu, with valgrind
  build-main:
    strategy:
      matrix:
        config: [ Debug, RelWithDebInfo ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install prereqs
      run: sudo apt install valgrind
    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.config}} -DVALGRIND=true -DTHREADING=true
        cmake --build ${{github.workspace}}/build --config ${{matrix.config}}
    - name: Run unit tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.config}} --output-on-failure
    - name: Run integration tests
      run: echo TBI
    - name: Run fuzz tests
      run: echo TBI
  # but we still want to test on Windows and Mac, and report if they failed
  build-alt:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest, macos-11 ]
        config: [ Debug, Release ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.config}}
        cmake --build ${{github.workspace}}/build --config ${{matrix.config}}
    - name: Run unit tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.config}} --output-on-failure
    - name: Run integration tests
      run: echo TBI
    - name: Run fuzz tests
      run: echo TBI
